name: DMM 素人ジャンル自動投稿

on:
  schedule:
    # UTCで21,1,5,9,13,17時に毎日実行（JSTの0/4/8/12/16/20時）
    - cron: '0 21,1,5,9,13,17 * * *'
  workflow_dispatch:  # 手動トリガーも可能

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 依存ライブラリはスクリプト内でセルフインストールするため、不要
      # - name: 依存ライブラリをインストール
      #   run: pip install -r requirements.txt

      - name: 自動投稿スクリプト実行
        env:
          WP_URL:           ${{ secrets.WP_URL }}
          WP_USER:          ${{ secrets.WP_USER }}
          WP_PASS:          ${{ secrets.WP_PASS }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          DMM_API_ID:       ${{ secrets.DMM_API_ID }}
        run: |
          python dmm_auto_post.py
