# .github/workflows/dmm_auto_post.yml
name: DMM → WordPress Auto Post

on:
  schedule:
    # UTC schedule for every 4 hours (00,04,08,12,16,20 JST → 15,19,23,03,07,11 UTC)
    - cron: '0 15,19,23,3,7,11 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-wordpress-xmlrpc python-dotenv beautifulsoup4 lxml

      - name: Run posting script
        env:
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          WP_URL:             ${{ secrets.WP_URL }}
          WP_USER:            ${{ secrets.WP_USER }}
          WP_PASS:            ${{ secrets.WP_PASS }}
        run: |
          python fetch_and_post.py
