steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
      cache: 'pip'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -V
      pip list | sed -n '1,80p'

  - name: Run FANZA Auto Post (REST固定テスト)
    env:
      WP_URL: ${{ secrets.WP_URL }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      DMM_API_ID: ${{ secrets.DMM_API_ID }}
      DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
      CATEGORY: ${{ secrets.CATEGORY }}
      TEST_PRODUCT_URL: "https://example.com/your-product"
      TEST_TITLE: "テスト投稿"
      TEST_TAGS: "タグA,タグB"
      TEST_IMAGES: "https://example.com/a.jpg,https://example.com/b.jpg"
    shell: bash
    run: |
      set -euo pipefail
      echo "WP_URL=$WP_URL"
      if [[ -z "${TEST_PRODUCT_URL}" || "${TEST_PRODUCT_URL}" == *"example.com/your-product"* ]]; then
        echo "::error ::TEST_PRODUCT_URL が未設定かプレースホルダです。YAML内を実URLに編集してから実行してね。"; exit 1;
      fi
      AUTH=$(printf "%s:%s" "$WP_USER" "$WP_APP_PASSWORD" | base64)
      TS=$(date +%s)
      echo "[AUTH-POST] $WP_URL/?rest_route=/wp/v2/tags"
      curl -sS -D - -o >(head -c 400) \
           -H "Authorization: Basic $AUTH" \
           -H "Content-Type: application/json" \
           -X POST \
           -d '{"name":"api-auth-check-'"$TS"'"}' \
           "$WP_URL/?rest_route=/wp/v2/tags" || true
      rm -f .posted.log || true
      python fanza_auto_post.py
