name: FANZA Auto Post (REST)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  auto_post:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test WordPress REST
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        run: |
          set -e
          echo "Try: $WP_URL/wp-json/"
          AUTH=$(printf "%s:%s" "$WP_USER" "$WP_APP_PASSWORD" | base64)
          curl -sS -D - -o /dev/null -H "Authorization: Basic $AUTH" -A "curl/REST-check" "$WP_URL/wp-json/"
          echo
          echo "Fallback: $WP_URL/?rest_route=/"
          curl -sS -D - -o /dev/null -H "Authorization: Basic $AUTH" -A "curl/REST-check" "$WP_URL/?rest_route=/"

      - name: Run FANZA auto post script
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          CATEGORY: ${{ secrets.CATEGORY }}
        run: python fanza_auto_post.py
