name: FANZA Auto Post

on:
  workflow_dispatch:      # 手動実行ボタンを出す
  schedule:               # 毎日JST 03:00 に自動実行
    - cron: '0 18 * * *'  

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests python-wordpress-xmlrpc pytz

      - name: Run FANZA Auto Post
        env:
          DMM_API_ID:       ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          WP_URL:           ${{ secrets.WP_URL }}
          WP_USER:          ${{ secrets.WP_USER }}
          WP_PASS:          ${{ secrets.WP_PASS }}
          CATEGORY:         ${{ secrets.CATEGORY }}
        run: python fanza_auto_post.py
