name: FANZA Auto Post

on:
  workflow_dispatch:

jobs:
  fanza:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install selenium python-wordpress-xmlrpc requests pytz

      - name: DEBUG: grep for 'from collections import Iterable' in site-packages
        run: |
          grep -r "from collections import Iterable" $(python -c "import site; print(site.getsitepackages()[0])") || true

      - name: Run FANZA Selenium Scraper
        env:
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}
          CATEGORY: ${{ secrets.CATEGORY }}
        run: python fanza_auto_post.py
