      - name: Run auto poster
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          CATEGORY: ${{ secrets.CATEGORY }}

          # ▼テスト固定値（一時的）
          TEST_PRODUCT_URL: "https://example.com/your-product"
          TEST_TITLE: "テスト投稿"
          TEST_TAGS: "タグA,タグB"
          TEST_IMAGES: "https://example.com/a.jpg,https://example.com/b.jpg"
        run: python fanza_auto_post.py
