name: WordPress Auto Post (REST本番)

on:
  workflow_dispatch:
    inputs:
      test_product_url:
        description: "(任意) 単発テスト用の商品URL"
        required: false
      test_title:
        description: "(任意) テスト投稿タイトル"
        required: false
      test_tags:
        description: "(任意) カンマ区切りのタグ"
        required: false
      test_images:
        description: "(任意) カンマ区切りの画像URL（先頭がアイキャッチ）"
        required: false
  schedule:
    - cron: '0 */4 * * *'

jobs:
  auto-post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WordPress Auto Post (REST)
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          CATEGORY: ${{ secrets.CATEGORY }}
          TEST_PRODUCT_URL: ${{ github.event.inputs.test_product_url }}
          TEST_TITLE: ${{ github.event.inputs.test_title }}
          TEST_TAGS: ${{ github.event.inputs.test_tags }}
          TEST_IMAGES: ${{ github.event.inputs.test_images }}
        run: |
          echo "import re" >> fanza_auto_post.py
          python fanza_auto_post.py
