name: WordPress Auto Post (REST版・固定テスト入力B + デバッグ/ガード)

on:
workflow_dispatch:
schedule:
- cron: '0 * * * *'  # 毎時実行（必要に応じて変更）

jobs:
auto-post:
runs-on: ubuntu-latest
timeout-minutes: 30
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'
      cache: 'pip'

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python -V
      pip list | sed -n '1,80p'

  # ▼ 固定テスト入力（B案）：ここを必ず編集してから実行してください
  - name: Run FANZA Auto Post (REST固定テスト)
    env:
      # ▼ WordPress（REST用）
      WP_URL: ${{ secrets.WP_URL }}            # 例: https://example.com （/wp-json は付けない）
      WP_USER: ${{ secrets.WP_USER }}          # ログインユーザー名
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}  # Application Password

      # ▼ その他Secrets
      DMM_API_ID: ${{ secrets.DMM_API_ID }}
      DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
      CATEGORY: ${{ secrets.CATEGORY }}

      # ▼ 固定のテスト入力（B案）：★必ず実URLに差し替えてね
      TEST_PRODUCT_URL: "https://video.dmm.co.jp/amateur/content/?id=ppg017&i3_ref=list&i3_pst=1&dmmref=amateur_list"    # ★商品ページURL（差し替え必須）
      TEST_TITLE: "テスト投稿"
      TEST_TAGS: "タグA,タグB"
      TEST_IMAGES: "https://awsimgsrc.dmm.co.jp/pics_dig/digital/amateur/ppg017/ppg017jp-001.jpg?f=webp"
    shell: bash
    run: |
      set -euo pipefail
      echo "WP_URL=$WP_URL"
      # --- ガード：プレースホルダURLのままならエラーで止める ---
      if [[ -z "${TEST_PRODUCT_URL}" || "${TEST_PRODUCT_URL}" == *"example.com/your-product"* ]]; then
        echo "::error ::TEST_PRODUCT_URL が未設定かプレースホルダです。YAML内を実URLに編集してから実行してね。"; exit 1;
      fi

      # --- 認証デバッグ（POSTのみ）---
      AUTH=$(printf "%s:%s" "$WP_USER" "$WP_APP_PASSWORD" | base64)
      TS=$(date +%s)
      echo "[AUTH-POST] $WP_URL/?rest_route=/wp/v2/tags"
      curl -sS -D - -o >(head -c 400) \
           -H "Authorization: Basic $AUTH" \
           -H "Content-Type: application/json" \
           -X POST \
           -d '{"name":"api-auth-check-'"$TS"'"}' \
           "$WP_URL/?rest_route=/wp/v2/tags" || true

      # --- 一時的に重複ログを掃除（必要に応じて外してOK）---
      rm -f .posted.log || true

      # --- 本処理 ---
      python fanza_auto_post.py
