      - name: Run FANZA auto post script
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          WP_PASS: ${{ secrets.WP_PASS }}   # 追加
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
          CATEGORY: ${{ secrets.CATEGORY }}
          TEST_PRODUCT_URL: ${{ inputs.test_product_url }}
          TEST_TITLE: ${{ inputs.test_title }}
          TEST_TAGS: ${{ inputs.test_tags }}
          TEST_IMAGES: ${{ inputs.test_images }}
