name: FANZA Auto Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'   # 今の頻度は踏襲（）

jobs:
  auto_post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run auto poster
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}          # Application Passwordとペアにする
          WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
          CATEGORY: ${{ secrets.CATEGORY }}
          DMM_API_ID: ${{ secrets.DMM_API_ID }}
          DMM_AFFILIATE_ID: ${{ secrets.DMM_AFFILIATE_ID }}
        run: python fanza_auto_post.py
