name: FANZA Auto Post (XML-RPC)

on:
  workflow_dispatch:
    inputs:
      test_product_url:
        description: "単発テスト用の商品URL（入れたら1件投稿）"
        required: false
      test_title:
        description: "テスト投稿タイトル（任意）"
        required: false
      test_tags:
        description: "カンマ区切りタグ（任意）"
        required: false
      test_images:
        description: "カンマ区切りの画像URL（任意｜先頭が本文先頭に表示）"
        required: false

jobs:
  auto-post:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run FANZA Auto Post (XML-RPC)
        env:
          WP_URL: ${{ secrets.WP_URL }}      # 例: https://example.com
          WP_USER: ${{ secrets.WP_USER }}
          WP_PASS: ${{ secrets.WP_PASS }}    # 追加済み？（未設定だとKeyError）
          CATEGORY: ${{ secrets.CATEGORY }}
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}
          TAG_IDS: ${{ secrets.TAG_IDS }}

          TEST_PRODUCT_URL: ${{ inputs.test_product_url }}
          TEST_TITLE: ${{ inputs.test_title }}
          TEST_TAGS: ${{ inputs.test_tags }}
          TEST_IMAGES: ${{ inputs.test_images }}
        run: python fanza_auto_post.py
