name: FANZA Auto Post (XML-RPC)

on:
  # 手動テスト用
  workflow_dispatch:
    inputs:
      test_product_url:
        description: "単発テスト用の商品URL（入れたら1件投稿）"
        required: false
      test_title:
        description: "テスト投稿タイトル（任意）"
        required: false
      test_tags:
        description: "カンマ区切りタグ（任意）"
        required: false
      test_images:
        description: "カンマ区切りの画像URL（任意｜先頭が本文先頭に表示）"
        required: false
  # 本番定期実行（必要になったらコメント解除）
  # schedule:
  #   - cron: '0 */4 * * *'  # 4時間おき（日本時間はGitHub基準とズレるので注意）

jobs:
  auto-post:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sed -n '1,30p' fanza_auto_post.py

      - name: Run FANZA Auto Post (XML-RPC)
        env:
          # ▼ WordPress 接続（XML‑RPC 版）
          # WP_URL はサイトルートでもOK（コード側で /xmlrpc.php を補完）
          WP_URL: ${{ secrets.WP_URL }}          # 例: https://example.com
          WP_USER: ${{ secrets.WP_USER }}        # WPのユーザー名
          WP_PASS: ${{ secrets.WP_PASS }}        # ユーザーのパス or アプリパス

          # ▼ 投稿先（任意）
          CATEGORY: ${{ secrets.CATEGORY }}      # 空でもOK
          CATEGORY_ID: ${{ secrets.CATEGORY_ID }}# 例: 3（既存カテゴリIDを付与したい時）
          TAG_IDS: ${{ secrets.TAG_IDS }}        # 例: 12,34（既存タグID）

          # ▼ 手動テスト入力（入れたら1件だけ投稿）
          TEST_PRODUCT_URL: ${{ inputs.test_product_url }}
          TEST_TITLE: ${{ inputs.test_title }}
          TEST_TAGS: ${{ inputs.test_tags }}
          TEST_IMAGES: ${{ inputs.test_images }}
        run: |
          python fanza_auto_post.py
